DaEnri/Acme-Recipes

src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Added danenrdia's favourite link

Task-01: Done

---

src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Added andvarbay's favourite link.

Task-02: Done

---

src/main/java/acme/roles/Chef.java
src/main/java/acme/roles/Epicure.java
src/main/webapp/WEB-INF/resources/initial-data/user-account.csv

Added Chef and Epicure entities and modified user-account.csv

Task-11: Done

---

src/main/java/acme/entities/Peep.java

Task-12: Done

---

src/main/java/acme/entities/Bulletin.java

Task-13: Done

---

src/main/java/acme/entities/Recipe.java

Añadida entidad "Recipe" y su relación con "Chef"

Task-16: Done

---

src/main/java/acme/entities/FineDish.java
src/main/java/acme/entities/Status.java

Añadida la entidad "FineDish", sus relaciones y el enumerado "Status"

Task-17: Done

---

src/main/java/acme/entities/Memorandum.java

Añadida la entidad "Memorandum" y su relación con "Fine Dish"

Task-18: Done

---

src/main/java/acme/entities/FineDish.java

Se ha modificado el mensaje del patrón del código

Task-17: Fix

---

src/main/java/acme/entities/KitchenItem.java
src/main/java/acme/entities/KitchenItemType.java
src/main/java/acme/entities/Quantity.java
src/main/java/acme/entities/Unit.java

Creación de la entidad KitchenItem, del enumerado KitchenItemType y de
la entidad Quantity para relacionar KitchenItem con Recipe.

Task-14 & Task-15: Done

---

reports/model.uxf

Modelo UML a falta de incluir los Dashboards.

Task-24: Partially done

---

src/main/java/acme/entities/Recipe.java

Se ha añadido el atributo "published" a la entidad "Recipe"

Task-16: Fix

---

src/main/java/acme/forms/EpicureDashboard.java

Añadida la entidad "EpicureDashboard"

Task-19: Done

---

src/main/java/acme/forms/AdminDashboard.java

Añadida entidad "AdminDashboard"

Task-20: Done

---

reports/model.uxf

Diagrama UML completo con los dashboards y el system configuration.

Task-24:Done

---

src/main/java/acme/features/any/peep/AnyPeepController.java
src/main/java/acme/features/any/peep/AnyPeepListService.java
src/main/java/acme/features/any/peep/AnyPeepRepository.java
src/main/webapp/WEB-INF/views/any/peep/list.jsp
src/main/webapp/WEB-INF/views/any/peep/messsages-en.i18n
src/main/webapp/WEB-INF/views/any/peep/messsages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Listado de recent peeps hecho.

Task-27: Done

---

src/main/java/acme/features/chef/kitchenItem/ChefIngredientListService.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemController.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemRepository.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemShowService.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenUtensilListService.java
src/main/webapp/WEB-INF/views/chef/kitchen-item/form.jsp
src/main/webapp/WEB-INF/views/chef/kitchen-item/list.jsp
src/main/webapp/WEB-INF/views/chef/kitchen-item/messsages-en.i18n
src/main/webapp/WEB-INF/views/chef/kitchen-item/messsages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Vistas de listado y detalles de los ingredientes y utensilios de cocina
propios de un chef.

Task-33 & Task-34: Done

---

src/main/java/acme/entities/FineDish.java
src/main/java/acme/features/chef/fineDish/ChefFineDishController.java
src/main/java/acme/features/chef/fineDish/ChefFineDishListService.java
src/main/java/acme/features/chef/fineDish/ChefFineDishRepository.java
src/main/java/acme/features/chef/fineDish/ChefFineDishShowService.java
src/main/webapp/WEB-INF/resources/sample-data/fine-dish.csv
src/main/webapp/WEB-INF/views/chef/fine-dish/form.jsp
src/main/webapp/WEB-INF/views/chef/fine-dish/list.jsp
src/main/webapp/WEB-INF/views/chef/fine-dish/messsages-en.i18n
src/main/webapp/WEB-INF/views/chef/fine-dish/messsages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Listado y detalles de fine dishes de un chef disponible. El enlace al
perfil del epicure no está disponible ya que no se ha implementado la
vista de los perfiles de usuario.

Task-36: Done

---

src/main/java/acme/features/any/userAccount/AnyUserAccountController.java
src/main/java/acme/features/any/userAccount/AnyUserAccountListService.java
src/main/java/acme/features/any/userAccount/AnyUserAccountRepository.java
src/main/java/acme/features/any/userAccount/AnyUserAccountShowService.java
src/main/webapp/WEB-INF/views/any/user-account/form.jsp
src/main/webapp/WEB-INF/views/any/user-account/list.jsp
src/main/webapp/WEB-INF/views/any/user-account/messages-en.i18n
src/main/webapp/WEB-INF/views/any/user-account/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ahora es posible acceder al listado de usuarios y sus detalles

Task-26: Done

---

src/main/webapp/WEB-INF/views/chef/fine-dish/form.jsp

Arreglado el enlace al perfil del epicure asociado al fine dish

Task-36: Fix

---

src/main/java/acme/features/chef/memorandum/ChefMemorandumController.java
src/main/java/acme/features/chef/memorandum/ChefMemorandumListService.java
src/main/java/acme/features/chef/memorandum/ChefMemorandumRepository.java
src/main/java/acme/features/chef/memorandum/ChefMemorandumShowService.java
src/main/webapp/WEB-INF/views/chef/memorandum/form.jsp
src/main/webapp/WEB-INF/views/chef/memorandum/list.jsp
src/main/webapp/WEB-INF/views/chef/memorandum/messsages-en.i18n
src/main/webapp/WEB-INF/views/chef/memorandum/messsages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Listado y detalles de los memorandums de los fine dishes de un chef
disponibles.

Task-37: Done

---

src/main/java/acme/features/epicure/memorandum/EpicureMemorandumController.java
src/main/java/acme/features/epicure/memorandum/EpicureMemorandumListService.java
src/main/java/acme/features/epicure/memorandum/EpicureMemorandumRepository.java
src/main/java/acme/features/epicure/memorandum/EpicureMemorandumShowService.java
src/main/webapp/WEB-INF/views/epicure/memorandum/form.jsp
src/main/webapp/WEB-INF/views/epicure/memorandum/list.jsp
src/main/webapp/WEB-INF/views/epicure/memorandum/messsages-en.i18n
src/main/webapp/WEB-INF/views/epicure/memorandum/messsages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Listado y detalles de memoranda de fine dishes de epicures disponibles.

Task-39: Done

---

src/main/java/acme/features/authenticated/bulletin/AuthenticatedBulletinController.java
src/main/java/acme/features/authenticated/bulletin/AuthenticatedBulletinListService.java
src/main/java/acme/features/authenticated/bulletin/AuthenticatedBulletinRepository.java
src/main/java/acme/features/authenticated/bulletin/AuthenticatedBulletinShowService.java
src/main/webapp/WEB-INF/views/authenticated/bulletin/form.jsp
src/main/webapp/WEB-INF/views/authenticated/bulletin/list.jsp
src/main/webapp/WEB-INF/views/authenticated/bulletin/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/bulletin/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ya es posible ver los boletines recientes si el usuario ha iniciado sesión

Task 31: Done

---

src/main/java/acme/features/authenticated/systemConfiguration/AuthenticatedSystemConfigrationController.java
src/main/java/acme/features/authenticated/systemConfiguration/AuthenticatedSystemConfigrationRepository.java
src/main/java/acme/features/authenticated/systemConfiguration/AuthenticatedSystemConfigrationShowService.java
src/main/webapp/WEB-INF/views/authenticated/system-configuration/form.jsp
src/main/webapp/WEB-INF/views/authenticated/system-configuration/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/system-configuration/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ahora es posible ver la información de las divisas del sistema para los usuarios autenticados

Task-32: Done

---

src/main/java/acme/features/administrator/systemConfiguration/AdministratorSystemConfigrationController.java
src/main/java/acme/features/administrator/systemConfiguration/AdministratorSystemConfigrationRepository.java
src/main/java/acme/features/administrator/systemConfiguration/AdministratorSystemConfigrationShowService.java
src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp
src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ya es posible que los administradores puedan ver la configuración del sistema

Task-41: Done

---

src/main/java/acme/features/epicure/epicureDashboard/EpicureEpicureDashboardController.java
src/main/java/acme/features/epicure/epicureDashboard/EpicureEpicureDashboardRepository.java
src/main/java/acme/features/epicure/epicureDashboard/EpicureEpicureDashboardShowService.java
src/main/webapp/WEB-INF/views/epicure/epicure-dashboard/form.jsp
src/main/webapp/WEB-INF/views/epicure/epicure-dashboard/messages-en.i18n
src/main/webapp/WEB-INF/views/epicure/epicure-dashboard/messages-es.i18n

Ahora es posible que los sibaritas puedan ver estadísticas sobre los platos finos

Task-40: Done

---

src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardController.java
src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardRepository.java
src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardShowService.java
src/main/java/acme/forms/AdminDashboard.java
src/main/webapp/WEB-INF/views/administrator/admin-dashboard/form.jsp
src/main/webapp/WEB-INF/views/administrator/admin-dashboard/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/admin-dashboard/messages-es.i18n

Ya es posible ver las estadisticas de administrador. Además, se ha arreglado la entidad asociada para que sea acorde a los requisitos

Task-42: Done

---

reports/model.uxf

Actualización del modelo UML con los cambios en adminDashboard

Task-24: Fix

---

src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Se ha añadido links en el menú para acceder a los dashboards

Task 40&42: Fix

---

src/main/java/acme/components/ExchangeRate.java
src/main/java/acme/features/authenticated/moneyExchange/AuthenticatedMoneyExchangeController.java
src/main/java/acme/features/authenticated/moneyExchange/AuthenticatedMoneyExchangePerformService.java
src/main/java/acme/forms/MoneyExchange.java
src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp
src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-es.i18n
src/main/webapp/WEB-INF/views/authenticated/money-exchange/form.jsp
src/main/webapp/WEB-INF/views/authenticated/money-exchange/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/money-exchange/messages-es.i18n
src/main/webapp/WEB-INF/views/authenticated/system-configuration/form.jsp
src/main/webapp/WEB-INF/views/authenticated/system-configuration/messages-en.i18n
src/main/webapp/WEB-INF/views/authenticated/system-configuration/messages-es.i18n

Se ha añadido las funcionalidades de intercambio de moneda

Money Exchange: Done

---

src/main/java/acme/features/any/kitchenItem/AnyKitchenItemController.java
src/main/java/acme/features/any/kitchenItem/AnyKitchenItemListIngredientService.java
src/main/java/acme/features/any/kitchenItem/AnyKitchenItemListKitchenUtensilService.java
src/main/java/acme/features/any/kitchenItem/AnyKitchenItemListRecipeFilterService.java
src/main/java/acme/features/any/kitchenItem/AnyKitchenItemRepository.java
src/main/java/acme/features/any/kitchenItem/AnyKitchenItemShowService.java
src/main/java/acme/features/any/recipe/AnyRecipeController.java
src/main/java/acme/features/any/recipe/AnyRecipeListKitchenItemFilterService.java
src/main/java/acme/features/any/recipe/AnyRecipeListService.java
src/main/java/acme/features/any/recipe/AnyRecipeRepository.java
src/main/java/acme/features/any/recipe/AnyRecipeShowService.java
src/main/webapp/WEB-INF/resources/sample-data/kitchen-item.csv
src/main/webapp/WEB-INF/views/any/kitchen-item/form.jsp
src/main/webapp/WEB-INF/views/any/kitchen-item/list.jsp
src/main/webapp/WEB-INF/views/any/kitchen-item/messsages-en.i18n
src/main/webapp/WEB-INF/views/any/kitchen-item/messsages-es.i18n
src/main/webapp/WEB-INF/views/any/recipe/form.jsp
src/main/webapp/WEB-INF/views/any/recipe/list.jsp
src/main/webapp/WEB-INF/views/any/recipe/messages-en.i18n
src/main/webapp/WEB-INF/views/any/recipe/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Se ha realizado todo lo relacionado con recetas para todos los usuarios además de arreglar varias cosas

Task 30: Done

---

src/main/java/acme/features/any/kitchenItem/AnyKitchenItemRepository.java
src/main/java/acme/features/any/recipe/AnyRecipeRepository.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemController.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemRecipeFilter.java
src/main/java/acme/features/chef/kitchenItem/ChefKitchenItemRepository.java
src/main/java/acme/features/chef/recipe/ChefRecipeController.java
src/main/java/acme/features/chef/recipe/ChefRecipeListService.java
src/main/java/acme/features/chef/recipe/ChefRecipeRepository.java
src/main/java/acme/features/chef/recipe/ChefRecipeShowService.java
src/main/webapp/WEB-INF/views/chef/recipe/form.jsp
src/main/webapp/WEB-INF/views/chef/recipe/list.jsp
src/main/webapp/WEB-INF/views/chef/recipe/messages-en.i18n
src/main/webapp/WEB-INF/views/chef/recipe/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ahora es posible que un chef vea sus recetas y los ingredientes/utensilios asociados a esas recetas
También se han realizado cambios en las vistas de cualquier usuario en recetas e items de cocina para que solo puedan verse los que han sido publicados

Task-35: Done & Task-30: Fixes

---

src/main/webapp/WEB-INF/views/administrator/admin-dashboard/messages-en.i18n

Se ha corregido varios comentarios en el dashboard de admins

Task-42: Fix

---

src/main/webapp/WEB-INF/views/any/recipe/form.jsp
src/main/webapp/WEB-INF/views/chef/recipe/form.jsp

Cambiado para que el link opcional se muestre incluso si no se ha especificado ninguno

Task-30 & 35: Done

---

src/main/java/acme/features/chef/fineDish/ChefFineDishController.java
src/main/java/acme/features/chef/fineDish/ChefFineDishUpdateService.java
src/main/webapp/WEB-INF/resources/sample-data/fine-dish.csv
src/main/webapp/WEB-INF/views/chef/fine-dish/form.jsp

Ahora un chef puede aceptar o rechazar un fine dish que haya sido
publicado y esté en estado de proposed.

Task-56: Done

---

src/main/java/acme/features/epicure/memorandum/EpicureMemorandumController.java
src/main/java/acme/features/epicure/memorandum/EpicureMemorandumCreateService.java
src/main/java/acme/features/epicure/memorandum/EpicureMemorandumRepository.java
src/main/webapp/WEB-INF/views/epicure/memorandum/form.jsp
src/main/webapp/WEB-INF/views/epicure/memorandum/list.jsp
src/main/webapp/WEB-INF/views/epicure/memorandum/messsages-en.i18n
src/main/webapp/WEB-INF/views/epicure/memorandum/messsages-es.i18n

Creación de memoranda por parte de un epicure implementada.

Task-59: Done

---

src/main/webapp/WEB-INF/views/anonymous/user-account/form.jsp
src/main/webapp/WEB-INF/views/anonymous/user-account/messages-en.i18n
src/main/webapp/WEB-INF/views/anonymous/user-account/messages-es.i18n

Ahora el sign up es operativo de nuevo

Task-50&51: Fix

---

src/main/java/acme/system/configuration/SystemConfiguration.java

Se ha añadido una restricccion que faltaba al spamThreshold de la configuración del sistema

Task-61: Fix

---

src/main/java/acme/features/administrator/bulletin/AdministratorBulletinController.java
src/main/java/acme/features/administrator/bulletin/AdministratorBulletinCreateService.java
src/main/java/acme/features/administrator/bulletin/AdministratorBulletinRepository.java
src/main/webapp/WEB-INF/views/administrator/bulletin/form.jsp
src/main/webapp/WEB-INF/views/administrator/bulletin/messages-en.i18n
src/main/webapp/WEB-INF/views/administrator/bulletin/messages-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
src/main/webapp/WEB-INF/views/fragments/menu.jsp

Ahora los administradores pueden crear boletines

Task-60: Done

---

src/main/java/acme/features/chef/quantity/ChefQuantityController.java
src/main/java/acme/features/chef/quantity/ChefQuantityCreateService.java
src/main/java/acme/features/chef/quantity/ChefQuantityDeleteService.java
src/main/java/acme/features/chef/quantity/ChefQuantityListService.java
src/main/java/acme/features/chef/quantity/ChefQuantityRepository.java
src/main/java/acme/features/chef/quantity/ChefQuantityShowService.java
src/main/java/acme/features/chef/quantity/ChefQuantityUpdateService.java
src/main/java/acme/features/chef/recipe/ChefRecipeController.java
src/main/java/acme/features/chef/recipe/ChefRecipeCreateService.java
src/main/java/acme/features/chef/recipe/ChefRecipeDeleteService.java
src/main/java/acme/features/chef/recipe/ChefRecipePublishService.java
src/main/java/acme/features/chef/recipe/ChefRecipeRepository.java
src/main/java/acme/features/chef/recipe/ChefRecipeUpdateService.java
src/main/webapp/WEB-INF/views/chef/quantity/form.jsp
src/main/webapp/WEB-INF/views/chef/quantity/list.jsp
src/main/webapp/WEB-INF/views/chef/quantity/messsages-en.i18n
src/main/webapp/WEB-INF/views/chef/quantity/messsages-es.i18n
src/main/webapp/WEB-INF/views/chef/recipe/form.jsp
src/main/webapp/WEB-INF/views/chef/recipe/list.jsp
src/main/webapp/WEB-INF/views/chef/recipe/messages-en.i18n
src/main/webapp/WEB-INF/views/chef/recipe/messages-es.i18n

Ya es posible crear, modificar, publicar y eliminar recetas. También es posible añadir, modificar y eliminar las cantidades y unidades de medida de los ingredientes de una receta

Task 55: Done
